requires = ["tox>=4.19"]
env_list = ["py314", "py313", "py312", "py311", "py310", "py39", "black"]


[pytest_collect]
description = "Only try to collect changes under python {base_python} to make sure test collection is ok."
deps = [
    "pytest",
    "mock",
    "pytest-mock",
    "sympy",
    "gmsh",
    "pyuff",
    "deap",
    "smoot",
    "git+https://github.com/mxgnsr/SciDataTool/tree/update-reqs.git",
]
# commands_pre = [""]
commands = [["pytest", "--co"]]

[env_run_base]
description = "Run test under {base_python}"
deps = [
    "pytest",
    "mock",
    "pytest-mock",
    "sympy",
    "gmsh",
    "pyuff",
    "deap",
    "smoot",
    "swat-em",
    "ddt",
    "nbformat",
    "nbconvert",
]
commands_pre = [
    [
        "pip",
        "uninstall",
        "scidatatool",
        "-y",
    ],
    [
        "pip",
        "install",
        "git+https://github.com/mxgnsr/SciDataTool.git@update-reqs",
    ],
]
commands = [["pytest", "Tests"]]

[env.black]
description = "run black linter on code base"
skip_install = true
deps = ["black>=24.0.0,<25.0.0"]
commands = [["black", "pyleecan"]]

# [env.type]
# description = "run type checks"
# deps = ["mypy"]
# commands = [
#     [
#         "mypy",
#         { replace = "posargs", default = [
#             "src",
#             "tests",
#         ], extend = true },
#     ],
# ]
