# -*- coding: utf-8 -*-

pixmap_dict = {
    "End_Random": ":/images/images/MachineSetup/WindParam/End_Random.PNG",
    "End_Preform": ":/images/images/MachineSetup/WindParam/End_Preform.PNG",
    "Dim_Ext_Rotor_mag": ":/images/images/MachineSetup/MachineDimension/Dimension_Stator_Rotor_mag.png",
    "Dim_In_Rotor_No_Shaft_mag": ":/images/images/MachineSetup/MachineDimension/Dimension_Rotor_Stator_mag.png",
    "Dim_In_Rotor_Shaft_mag": ":/images/images/MachineSetup/MachineDimension/Dimension_Shaft_Rotor_Stator_mag.png",
    "Dim_Ext_Rotor": ":/images/images/MachineSetup/MachineDimension/Dimension_Stator_Rotor.png",
    "Dim_In_Rotor_No_Shaft": ":/images/images/MachineSetup/MachineDimension/Dimension_Rotor_Stator.png",
    "Dim_In_Rotor_Shaft": ":/images/images/MachineSetup/MachineDimension/Dimension_Shaft_Rotor_Stator.png",
    "SCIM": ":/images/images/MachineSetup/MachineType/machine_SCIM.png",
    "DFIM": ":/images/images/MachineSetup/MachineType/DFIM.png",
    "SynRM": ":/images/images/MachineSetup/MachineType/machine_SynRM.png",
    "SPMSM": ":/images/images/MachineSetup/MachineType/machine_SPMSM.png",
    "IPMSM": ":/images/images/MachineSetup/MachineType/machine_IPMSM.png",
    "LSPM": ":/images/images/MachineSetup/MachineType/machine_LSPM.png",
    "WRSM": ":/images/images/MachineSetup/MachineType/WRSM.png",
    "cross": ":/images/images/icon/cross.png",
    "check": ":/images/images/icon/check.png",
    "search": ":/images/images/icon/search.png",
    "soft_icon": ":/images/images/icon/pyleecan_64.png",
    "Cond11": ":/images/images/MachineSetup/WindParam/CondType11.png",
    "Cond11_single": ":/images/images/MachineSetup/WindParam/CondType11_single.png",
    "Cond12": ":/images/images/MachineSetup/WindParam/CondType12.png",
    "Cond12_single": ":/images/images/MachineSetup/WindParam/CondType12_single.png",
    "SlotW23_constant_tooth_wedge_full": "/images/images/MachineSetup/WSlot/SlotW23_constant_tooth_wedge_full.png",
    "SlotW23_wedge_full.png": ":/images/images/MachineSetup/WSlot/SlotW23_wedge_full.png",
    "SlotW23_constant_tooth_wind": ":/images/images/MachineSetup/WSlot/SlotW23_constant_tooth_wind.png",
    "SlotW23_wind": ":/images/images/MachineSetup/WSlot/SlotW23_wind.png",
    "SlotW11_constant_tooth_wedge_full": ":/images/images/MachineSetup/WSlot/SlotW11_constant_tooth_wedge_full.png",
    "SlotW11_wedge_full": ":/images/images/MachineSetup/WSlot/SlotW11_wedge_full.png",
    "SlotW11_constant_tooth_wind": ":/images/images/MachineSetup/WSlot/SlotW11_constant_tooth_wind.png",
    "SlotW11_wind": ":/images/images/MachineSetup/WSlot/SlotW11_wind.png",
}
