# -*- coding: utf-8 -*-

REPERE_NAME = "XYZ1"
SHAFT_COLOR = "BLACK"
FRAME_COLOR = "MAGENTA"
S_LAM_COLOR = "TURQUOISE"
R_LAM_COLOR = "GREEN"
WIND_COLOR = "RED"
GAP_COLOR = "WHITE"
VENT_COLOR = "WHITE"
AIR_COLOR = "WHITE"
MAG_COLOR = "YELLOW"
