# -*- coding: utf-8 -*-

# File generated according to PHoleM57.ui
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PHoleM57(object):
    def setupUi(self, PHoleM57):
        PHoleM57.setObjectName("PHoleM57")
        PHoleM57.resize(700, 470)
        PHoleM57.setMinimumSize(QtCore.QSize(700, 470))
        PHoleM57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PHoleM57)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_slot = QtWidgets.QLabel(PHoleM57)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_slot.sizePolicy().hasHeightForWidth())
        self.img_slot.setSizePolicy(sizePolicy)
        self.img_slot.setMinimumSize(QtCore.QSize(450, 120))
        self.img_slot.setMaximumSize(QtCore.QSize(450, 120))
        self.img_slot.setText("")
        self.img_slot.setPixmap(
            QtGui.QPixmap(":/images/images/MachineSetup/WSlot/Slot_57.PNG")
        )
        self.img_slot.setScaledContents(True)
        self.img_slot.setObjectName("img_slot")
        self.verticalLayout_3.addWidget(self.img_slot)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lf_W3 = FloatEdit(PHoleM57)
        self.lf_W3.setObjectName("lf_W3")
        self.gridLayout.addWidget(self.lf_W3, 5, 1, 1, 1)
        self.lf_W0 = FloatEdit(PHoleM57)
        self.lf_W0.setObjectName("lf_W0")
        self.gridLayout.addWidget(self.lf_W0, 2, 1, 1, 1)
        self.in_W1 = QtWidgets.QLabel(PHoleM57)
        self.in_W1.setObjectName("in_W1")
        self.gridLayout.addWidget(self.in_W1, 3, 0, 1, 1)
        self.lf_H2 = FloatEdit(PHoleM57)
        self.lf_H2.setObjectName("lf_H2")
        self.gridLayout.addWidget(self.lf_H2, 1, 1, 1, 1)
        self.unit_W1 = QtWidgets.QLabel(PHoleM57)
        self.unit_W1.setObjectName("unit_W1")
        self.gridLayout.addWidget(self.unit_W1, 3, 2, 1, 1)
        self.lf_H1 = FloatEdit(PHoleM57)
        self.lf_H1.setObjectName("lf_H1")
        self.gridLayout.addWidget(self.lf_H1, 0, 1, 1, 1)
        self.unit_W2 = QtWidgets.QLabel(PHoleM57)
        self.unit_W2.setObjectName("unit_W2")
        self.gridLayout.addWidget(self.unit_W2, 4, 2, 1, 1)
        self.in_W3 = QtWidgets.QLabel(PHoleM57)
        self.in_W3.setObjectName("in_W3")
        self.gridLayout.addWidget(self.in_W3, 5, 0, 1, 1)
        self.unit_W4 = QtWidgets.QLabel(PHoleM57)
        self.unit_W4.setObjectName("unit_W4")
        self.gridLayout.addWidget(self.unit_W4, 6, 2, 1, 1)
        self.lf_W4 = FloatEdit(PHoleM57)
        self.lf_W4.setText("")
        self.lf_W4.setObjectName("lf_W4")
        self.gridLayout.addWidget(self.lf_W4, 6, 1, 1, 1)
        self.unit_W0 = QtWidgets.QLabel(PHoleM57)
        self.unit_W0.setObjectName("unit_W0")
        self.gridLayout.addWidget(self.unit_W0, 2, 2, 1, 1)
        self.in_W2 = QtWidgets.QLabel(PHoleM57)
        self.in_W2.setObjectName("in_W2")
        self.gridLayout.addWidget(self.in_W2, 4, 0, 1, 1)
        self.in_W0 = QtWidgets.QLabel(PHoleM57)
        self.in_W0.setObjectName("in_W0")
        self.gridLayout.addWidget(self.in_W0, 2, 0, 1, 1)
        self.in_W4 = QtWidgets.QLabel(PHoleM57)
        self.in_W4.setObjectName("in_W4")
        self.gridLayout.addWidget(self.in_W4, 6, 0, 1, 1)
        self.unit_H1 = QtWidgets.QLabel(PHoleM57)
        self.unit_H1.setObjectName("unit_H1")
        self.gridLayout.addWidget(self.unit_H1, 0, 2, 1, 1)
        self.in_H2 = QtWidgets.QLabel(PHoleM57)
        self.in_H2.setObjectName("in_H2")
        self.gridLayout.addWidget(self.in_H2, 1, 0, 1, 1)
        self.lf_W2 = FloatEdit(PHoleM57)
        self.lf_W2.setObjectName("lf_W2")
        self.gridLayout.addWidget(self.lf_W2, 4, 1, 1, 1)
        self.in_H1 = QtWidgets.QLabel(PHoleM57)
        self.in_H1.setObjectName("in_H1")
        self.gridLayout.addWidget(self.in_H1, 0, 0, 1, 1)
        self.unit_W3 = QtWidgets.QLabel(PHoleM57)
        self.unit_W3.setObjectName("unit_W3")
        self.gridLayout.addWidget(self.unit_W3, 5, 2, 1, 1)
        self.lf_W1 = FloatEdit(PHoleM57)
        self.lf_W1.setObjectName("lf_W1")
        self.gridLayout.addWidget(self.lf_W1, 3, 1, 1, 1)
        self.unit_H2 = QtWidgets.QLabel(PHoleM57)
        self.unit_H2.setObjectName("unit_H2")
        self.gridLayout.addWidget(self.unit_H2, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.w_mat_0 = WMatSelect(PHoleM57)
        self.w_mat_0.setMinimumSize(QtCore.QSize(100, 0))
        self.w_mat_0.setObjectName("w_mat_0")
        self.verticalLayout_2.addWidget(self.w_mat_0)
        self.w_mat_1 = WMatSelect(PHoleM57)
        self.w_mat_1.setMinimumSize(QtCore.QSize(100, 0))
        self.w_mat_1.setObjectName("w_mat_1")
        self.verticalLayout_2.addWidget(self.w_mat_1)
        self.g_output = QtWidgets.QGroupBox(PHoleM57)
        self.g_output.setMinimumSize(QtCore.QSize(200, 0))
        self.g_output.setObjectName("g_output")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.g_output)
        self.verticalLayout.setObjectName("verticalLayout")
        self.out_slot_surface = QtWidgets.QLabel(self.g_output)
        self.out_slot_surface.setObjectName("out_slot_surface")
        self.verticalLayout.addWidget(self.out_slot_surface)
        self.out_magnet_surface = QtWidgets.QLabel(self.g_output)
        self.out_magnet_surface.setObjectName("out_magnet_surface")
        self.verticalLayout.addWidget(self.out_magnet_surface)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.g_output)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(PHoleM57)
        QtCore.QMetaObject.connectSlotsByName(PHoleM57)
        PHoleM57.setTabOrder(self.lf_H1, self.lf_H2)
        PHoleM57.setTabOrder(self.lf_H2, self.lf_W0)
        PHoleM57.setTabOrder(self.lf_W0, self.lf_W1)
        PHoleM57.setTabOrder(self.lf_W1, self.lf_W2)
        PHoleM57.setTabOrder(self.lf_W2, self.lf_W3)
        PHoleM57.setTabOrder(self.lf_W3, self.lf_W4)

    def retranslateUi(self, PHoleM57):
        _translate = QtCore.QCoreApplication.translate
        PHoleM57.setWindowTitle(_translate("PHoleM57", "Form"))
        self.in_W1.setText(_translate("PHoleM57", "W1 :"))
        self.unit_W1.setText(_translate("PHoleM57", "m"))
        self.unit_W2.setText(_translate("PHoleM57", "m"))
        self.in_W3.setText(_translate("PHoleM57", "W3 :"))
        self.unit_W4.setText(_translate("PHoleM57", "m"))
        self.unit_W0.setText(_translate("PHoleM57", "rad"))
        self.in_W2.setText(_translate("PHoleM57", "W2 :"))
        self.in_W0.setText(_translate("PHoleM57", "W0 :"))
        self.in_W4.setText(_translate("PHoleM57", "W4 :"))
        self.unit_H1.setText(_translate("PHoleM57", "m"))
        self.in_H2.setText(_translate("PHoleM57", "H2 :"))
        self.in_H1.setText(_translate("PHoleM57", "H1 :"))
        self.unit_W3.setText(_translate("PHoleM57", "m"))
        self.unit_H2.setText(_translate("PHoleM57", "m"))
        self.g_output.setTitle(_translate("PHoleM57", "Output"))
        self.out_slot_surface.setText(
            _translate("PHoleM57", "Slot suface (2 part) : ?")
        )
        self.out_magnet_surface.setText(
            _translate("PHoleM57", "Single Magnet surface : ?")
        )


from ......GUI.Dialog.DMatLib.WMatSelect.WMatSelect import WMatSelect
from pyleecan.GUI.Tools.FloatEdit import FloatEdit
from pyleecan.GUI.Resources import pyleecan_rc
