# -*- coding: utf-8 -*-

# File generated according to PWSlot61.ui
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PWSlot61(object):
    def setupUi(self, PWSlot61):
        PWSlot61.setObjectName("PWSlot61")
        PWSlot61.resize(630, 470)
        PWSlot61.setMinimumSize(QtCore.QSize(630, 470))
        PWSlot61.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PWSlot61)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img_slot = QtWidgets.QLabel(PWSlot61)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_slot.sizePolicy().hasHeightForWidth())
        self.img_slot.setSizePolicy(sizePolicy)
        self.img_slot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img_slot.setText("")
        self.img_slot.setPixmap(
            QtGui.QPixmap(":/images/images/MachineSetup/WSlot/Slot_61.PNG")
        )
        self.img_slot.setScaledContents(True)
        self.img_slot.setObjectName("img_slot")
        self.verticalLayout_2.addWidget(self.img_slot)
        self.txt_constraint = QtWidgets.QTextEdit(PWSlot61)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.txt_constraint.sizePolicy().hasHeightForWidth()
        )
        self.txt_constraint.setSizePolicy(sizePolicy)
        self.txt_constraint.setMaximumSize(QtCore.QSize(16777215, 70))
        self.txt_constraint.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_constraint.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse
        )
        self.txt_constraint.setObjectName("txt_constraint")
        self.verticalLayout_2.addWidget(self.txt_constraint)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.in_W0 = QtWidgets.QLabel(PWSlot61)
        self.in_W0.setObjectName("in_W0")
        self.gridLayout.addWidget(self.in_W0, 0, 0, 1, 1)
        self.lf_W0 = FloatEdit(PWSlot61)
        self.lf_W0.setObjectName("lf_W0")
        self.gridLayout.addWidget(self.lf_W0, 0, 1, 1, 1)
        self.unit_W0 = QtWidgets.QLabel(PWSlot61)
        self.unit_W0.setObjectName("unit_W0")
        self.gridLayout.addWidget(self.unit_W0, 0, 2, 1, 1)
        self.in_W1 = QtWidgets.QLabel(PWSlot61)
        self.in_W1.setObjectName("in_W1")
        self.gridLayout.addWidget(self.in_W1, 1, 0, 1, 1)
        self.lf_W1 = FloatEdit(PWSlot61)
        self.lf_W1.setObjectName("lf_W1")
        self.gridLayout.addWidget(self.lf_W1, 1, 1, 1, 1)
        self.unit_W1 = QtWidgets.QLabel(PWSlot61)
        self.unit_W1.setObjectName("unit_W1")
        self.gridLayout.addWidget(self.unit_W1, 1, 2, 1, 1)
        self.in_W2 = QtWidgets.QLabel(PWSlot61)
        self.in_W2.setObjectName("in_W2")
        self.gridLayout.addWidget(self.in_W2, 2, 0, 1, 1)
        self.lf_W2 = FloatEdit(PWSlot61)
        self.lf_W2.setObjectName("lf_W2")
        self.gridLayout.addWidget(self.lf_W2, 2, 1, 1, 1)
        self.unit_W2 = QtWidgets.QLabel(PWSlot61)
        self.unit_W2.setObjectName("unit_W2")
        self.gridLayout.addWidget(self.unit_W2, 2, 2, 1, 1)
        self.in_H0 = QtWidgets.QLabel(PWSlot61)
        self.in_H0.setObjectName("in_H0")
        self.gridLayout.addWidget(self.in_H0, 3, 0, 1, 1)
        self.lf_H0 = FloatEdit(PWSlot61)
        self.lf_H0.setObjectName("lf_H0")
        self.gridLayout.addWidget(self.lf_H0, 3, 1, 1, 1)
        self.unit_H0 = QtWidgets.QLabel(PWSlot61)
        self.unit_H0.setObjectName("unit_H0")
        self.gridLayout.addWidget(self.unit_H0, 3, 2, 1, 1)
        self.in_H1 = QtWidgets.QLabel(PWSlot61)
        self.in_H1.setObjectName("in_H1")
        self.gridLayout.addWidget(self.in_H1, 4, 0, 1, 1)
        self.lf_H1 = FloatEdit(PWSlot61)
        self.lf_H1.setObjectName("lf_H1")
        self.gridLayout.addWidget(self.lf_H1, 4, 1, 1, 1)
        self.unit_H1 = QtWidgets.QLabel(PWSlot61)
        self.unit_H1.setObjectName("unit_H1")
        self.gridLayout.addWidget(self.unit_H1, 4, 2, 1, 1)
        self.in_H2 = QtWidgets.QLabel(PWSlot61)
        self.in_H2.setObjectName("in_H2")
        self.gridLayout.addWidget(self.in_H2, 5, 0, 1, 1)
        self.lf_H2 = FloatEdit(PWSlot61)
        self.lf_H2.setObjectName("lf_H2")
        self.gridLayout.addWidget(self.lf_H2, 5, 1, 1, 1)
        self.unit_H2 = QtWidgets.QLabel(PWSlot61)
        self.unit_H2.setObjectName("unit_H2")
        self.gridLayout.addWidget(self.unit_H2, 5, 2, 1, 1)
        self.in_H3 = QtWidgets.QLabel(PWSlot61)
        self.in_H3.setObjectName("in_H3")
        self.gridLayout.addWidget(self.in_H3, 6, 0, 1, 1)
        self.lf_H3 = FloatEdit(PWSlot61)
        self.lf_H3.setObjectName("lf_H3")
        self.gridLayout.addWidget(self.lf_H3, 6, 1, 1, 1)
        self.unit_H3 = QtWidgets.QLabel(PWSlot61)
        self.unit_H3.setObjectName("unit_H3")
        self.gridLayout.addWidget(self.unit_H3, 6, 2, 1, 1)
        self.in_H4 = QtWidgets.QLabel(PWSlot61)
        self.in_H4.setObjectName("in_H4")
        self.gridLayout.addWidget(self.in_H4, 7, 0, 1, 1)
        self.lf_H4 = FloatEdit(PWSlot61)
        self.lf_H4.setObjectName("lf_H4")
        self.gridLayout.addWidget(self.lf_H4, 7, 1, 1, 1)
        self.unit_H4 = QtWidgets.QLabel(PWSlot61)
        self.unit_H4.setObjectName("unit_H4")
        self.gridLayout.addWidget(self.unit_H4, 7, 2, 1, 1)
        self.in_W3 = QtWidgets.QLabel(PWSlot61)
        self.in_W3.setObjectName("in_W3")
        self.gridLayout.addWidget(self.in_W3, 8, 0, 1, 1)
        self.lf_W3 = FloatEdit(PWSlot61)
        self.lf_W3.setObjectName("lf_W3")
        self.gridLayout.addWidget(self.lf_W3, 8, 1, 1, 1)
        self.unit_W3 = QtWidgets.QLabel(PWSlot61)
        self.unit_W3.setObjectName("unit_W3")
        self.gridLayout.addWidget(self.unit_W3, 8, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.g_output = QtWidgets.QGroupBox(PWSlot61)
        self.g_output.setMinimumSize(QtCore.QSize(200, 0))
        self.g_output.setObjectName("g_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.g_output)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.out_Wlam = QtWidgets.QLabel(self.g_output)
        self.out_Wlam.setObjectName("out_Wlam")
        self.verticalLayout_3.addWidget(self.out_Wlam)
        self.out_slot_height = QtWidgets.QLabel(self.g_output)
        self.out_slot_height.setObjectName("out_slot_height")
        self.verticalLayout_3.addWidget(self.out_slot_height)
        self.out_yoke_height = QtWidgets.QLabel(self.g_output)
        self.out_yoke_height.setObjectName("out_yoke_height")
        self.verticalLayout_3.addWidget(self.out_yoke_height)
        self.out_wind_surface = QtWidgets.QLabel(self.g_output)
        self.out_wind_surface.setObjectName("out_wind_surface")
        self.verticalLayout_3.addWidget(self.out_wind_surface)
        self.out_tot_surface = QtWidgets.QLabel(self.g_output)
        self.out_tot_surface.setObjectName("out_tot_surface")
        self.verticalLayout_3.addWidget(self.out_tot_surface)
        self.out_op_angle = QtWidgets.QLabel(self.g_output)
        self.out_op_angle.setObjectName("out_op_angle")
        self.verticalLayout_3.addWidget(self.out_op_angle)
        self.out_tooth_width = QtWidgets.QLabel(self.g_output)
        self.out_tooth_width.setObjectName("out_tooth_width")
        self.verticalLayout_3.addWidget(self.out_tooth_width)
        self.verticalLayout.addWidget(self.g_output)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(PWSlot61)
        QtCore.QMetaObject.connectSlotsByName(PWSlot61)
        PWSlot61.setTabOrder(self.lf_W0, self.lf_W1)
        PWSlot61.setTabOrder(self.lf_W1, self.lf_W2)
        PWSlot61.setTabOrder(self.lf_W2, self.lf_H0)
        PWSlot61.setTabOrder(self.lf_H0, self.lf_H1)
        PWSlot61.setTabOrder(self.lf_H1, self.lf_H2)
        PWSlot61.setTabOrder(self.lf_H2, self.txt_constraint)

    def retranslateUi(self, PWSlot61):
        _translate = QtCore.QCoreApplication.translate
        PWSlot61.setWindowTitle(_translate("PWSlot61", "Form"))
        self.txt_constraint.setHtml(
            _translate(
                "PWSlot61",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Constraints :</span></p>\n'
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">W2 &lt; W1</span></p></body></html>',
            )
        )
        self.in_W0.setText(_translate("PWSlot61", "W0 :"))
        self.unit_W0.setText(_translate("PWSlot61", "m"))
        self.in_W1.setText(_translate("PWSlot61", "W1 :"))
        self.unit_W1.setText(_translate("PWSlot61", "m"))
        self.in_W2.setText(_translate("PWSlot61", "W2 :"))
        self.unit_W2.setText(_translate("PWSlot61", "m"))
        self.in_H0.setText(_translate("PWSlot61", "H0 :"))
        self.unit_H0.setText(_translate("PWSlot61", "m"))
        self.in_H1.setText(_translate("PWSlot61", "H1 :"))
        self.unit_H1.setText(_translate("PWSlot61", "m"))
        self.in_H2.setText(_translate("PWSlot61", "H2 :"))
        self.unit_H2.setText(_translate("PWSlot61", "m"))
        self.in_H3.setText(_translate("PWSlot61", "d_coil_pole_top :"))
        self.unit_H3.setText(_translate("PWSlot61", "m"))
        self.in_H4.setText(_translate("PWSlot61", "d_coil_pole_bot :"))
        self.unit_H4.setText(_translate("PWSlot61", "m"))
        self.in_W3.setText(_translate("PWSlot61", "d_coil_pole_edg :"))
        self.unit_W3.setText(_translate("PWSlot61", "m"))
        self.g_output.setTitle(_translate("PWSlot61", "Output"))
        self.out_Wlam.setText(_translate("PWSlot61", "Lamination width : ?"))
        self.out_slot_height.setText(_translate("PWSlot61", "Slot height : ?"))
        self.out_yoke_height.setText(_translate("PWSlot61", "Yoke height : ?"))
        self.out_wind_surface.setText(_translate("PWSlot61", "Winding surface : ?"))
        self.out_tot_surface.setText(_translate("PWSlot61", "Total surface : ?"))
        self.out_op_angle.setText(_translate("PWSlot61", "Opening angle : ?"))
        self.out_tooth_width.setText(_translate("PWSlot61", "Tooth average width : ?"))


from ......GUI.Tools.FloatEdit import FloatEdit
from ......GUI.Resources import pyleecan_rc
