# -*- coding: utf-8 -*-

# File generated according to SLamParam.ui
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SLamParam(object):
    def setupUi(self, SLamParam):
        SLamParam.setObjectName("SLamParam")
        SLamParam.resize(650, 550)
        SLamParam.setMinimumSize(QtCore.QSize(650, 550))
        self.main_layout = QtWidgets.QVBoxLayout(SLamParam)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.in_L1 = QtWidgets.QLabel(SLamParam)
        self.in_L1.setObjectName("in_L1")
        self.horizontalLayout.addWidget(self.in_L1)
        self.lf_L1 = FloatEdit(SLamParam)
        self.lf_L1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lf_L1.setObjectName("lf_L1")
        self.horizontalLayout.addWidget(self.lf_L1)
        self.unit_L1 = QtWidgets.QLabel(SLamParam)
        self.unit_L1.setObjectName("unit_L1")
        self.horizontalLayout.addWidget(self.unit_L1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.main_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.in_Kf1 = QtWidgets.QLabel(SLamParam)
        self.in_Kf1.setObjectName("in_Kf1")
        self.horizontalLayout_2.addWidget(self.in_Kf1)
        self.lf_Kf1 = FloatEdit(SLamParam)
        self.lf_Kf1.setMaximumSize(QtCore.QSize(100, 25))
        self.lf_Kf1.setObjectName("lf_Kf1")
        self.horizontalLayout_2.addWidget(self.lf_Kf1)
        self.w_mat = WMatSelect(SLamParam)
        self.w_mat.setMinimumSize(QtCore.QSize(100, 0))
        self.w_mat.setObjectName("w_mat")
        self.horizontalLayout_2.addWidget(self.w_mat)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.main_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.g_ax_vent = QtWidgets.QGroupBox(SLamParam)
        self.g_ax_vent.setMinimumSize(QtCore.QSize(300, 300))
        self.g_ax_vent.setCheckable(True)
        self.g_ax_vent.setChecked(False)
        self.g_ax_vent.setObjectName("g_ax_vent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.g_ax_vent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.g_ax_vent)
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap(":/images/images/MachineSetup/LamParam/CircVentDuct.png")
        )
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.out_axial_duct = QtWidgets.QLabel(self.g_ax_vent)
        self.out_axial_duct.setObjectName("out_axial_duct")
        self.horizontalLayout_5.addWidget(self.out_axial_duct)
        self.b_axial_duct = QtWidgets.QPushButton(self.g_ax_vent)
        self.b_axial_duct.setObjectName("b_axial_duct")
        self.horizontalLayout_5.addWidget(self.b_axial_duct)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.g_ax_vent)
        self.g_rad_vent = QtWidgets.QGroupBox(SLamParam)
        self.g_rad_vent.setMinimumSize(QtCore.QSize(0, 300))
        self.g_rad_vent.setFlat(False)
        self.g_rad_vent.setCheckable(True)
        self.g_rad_vent.setChecked(False)
        self.g_rad_vent.setObjectName("g_rad_vent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.g_rad_vent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img_rad_duct = QtWidgets.QLabel(self.g_rad_vent)
        self.img_rad_duct.setMinimumSize(QtCore.QSize(300, 0))
        self.img_rad_duct.setText("")
        self.img_rad_duct.setPixmap(
            QtGui.QPixmap(":/images/images/MachineSetup/LamParam/RadVentDuct.png")
        )
        self.img_rad_duct.setScaledContents(True)
        self.img_rad_duct.setObjectName("img_rad_duct")
        self.verticalLayout_2.addWidget(self.img_rad_duct)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.in_Nrvd = QtWidgets.QLabel(self.g_rad_vent)
        self.in_Nrvd.setObjectName("in_Nrvd")
        self.horizontalLayout_4.addWidget(self.in_Nrvd)
        self.si_Nrvd = QtWidgets.QSpinBox(self.g_rad_vent)
        self.si_Nrvd.setMaximum(999)
        self.si_Nrvd.setProperty("value", 0)
        self.si_Nrvd.setObjectName("si_Nrvd")
        self.horizontalLayout_4.addWidget(self.si_Nrvd)
        self.in_Wrvd = QtWidgets.QLabel(self.g_rad_vent)
        self.in_Wrvd.setObjectName("in_Wrvd")
        self.horizontalLayout_4.addWidget(self.in_Wrvd)
        self.lf_Wrvd = FloatEdit(self.g_rad_vent)
        self.lf_Wrvd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lf_Wrvd.setObjectName("lf_Wrvd")
        self.horizontalLayout_4.addWidget(self.lf_Wrvd)
        self.unit_Wrvd = QtWidgets.QLabel(self.g_rad_vent)
        self.unit_Wrvd.setObjectName("unit_Wrvd")
        self.horizontalLayout_4.addWidget(self.unit_Wrvd)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.out_length = QtWidgets.QLabel(self.g_rad_vent)
        self.out_length.setMinimumSize(QtCore.QSize(250, 0))
        self.out_length.setMaximumSize(QtCore.QSize(300, 16777215))
        self.out_length.setObjectName("out_length")
        self.verticalLayout_2.addWidget(self.out_length)
        self.horizontalLayout_3.addWidget(self.g_rad_vent)
        self.main_layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem4)
        self.b_plot = QtWidgets.QPushButton(SLamParam)
        self.b_plot.setObjectName("b_plot")
        self.horizontalLayout_6.addWidget(self.b_plot)
        self.b_previous = QtWidgets.QPushButton(SLamParam)
        self.b_previous.setObjectName("b_previous")
        self.horizontalLayout_6.addWidget(self.b_previous)
        self.b_next = QtWidgets.QPushButton(SLamParam)
        self.b_next.setObjectName("b_next")
        self.horizontalLayout_6.addWidget(self.b_next)
        self.main_layout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(SLamParam)
        QtCore.QMetaObject.connectSlotsByName(SLamParam)
        SLamParam.setTabOrder(self.lf_L1, self.lf_Kf1)
        SLamParam.setTabOrder(self.lf_Kf1, self.b_next)
        SLamParam.setTabOrder(self.b_next, self.si_Nrvd)
        SLamParam.setTabOrder(self.si_Nrvd, self.lf_Wrvd)

    def retranslateUi(self, SLamParam):
        _translate = QtCore.QCoreApplication.translate
        SLamParam.setWindowTitle(_translate("SLamParam", "Form"))
        self.in_L1.setText(_translate("SLamParam", "L1 :"))
        self.unit_L1.setText(_translate("SLamParam", "m"))
        self.in_Kf1.setText(_translate("SLamParam", "Kf1 :"))
        self.g_ax_vent.setTitle(_translate("SLamParam", "Axial Ventilation Ducts"))
        self.out_axial_duct.setText(_translate("SLamParam", "Axial : 0 set (0 ducts)"))
        self.b_axial_duct.setText(_translate("SLamParam", "set axial ducts"))
        self.g_rad_vent.setTitle(_translate("SLamParam", "Radial Ventilation Ducts"))
        self.in_Nrvd.setText(_translate("SLamParam", "Nrvd :"))
        self.in_Wrvd.setText(_translate("SLamParam", "Wrvd :"))
        self.unit_Wrvd.setText(_translate("SLamParam", "m"))
        self.out_length.setText(
            _translate("SLamParam", "stator total length = L1 + Nrvd * Wrvd = ?")
        )
        self.b_plot.setText(_translate("SLamParam", "Preview"))
        self.b_previous.setText(_translate("SLamParam", "Previous"))
        self.b_next.setText(_translate("SLamParam", "Next"))


from pyleecan.GUI.Dialog.DMatLib.WMatSelect.WMatSelect import WMatSelect
from pyleecan.GUI.Tools.FloatEdit import FloatEdit
from pyleecan.GUI.Resources import pyleecan_rc
