def get_wave(self):
    """Return the wave generated by the Drive

    Parameters
    ----------
    self : DriveWave
        A DriveWave object

    Returns
    -------
    wave : ndarray
        Voltage / current waveform (Nt, qs)
    """

    return self.wave.get_data()
